version: '3.1'

services:


  wordpress:
    image: wordpress
    restart: always
    ports: 
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb      
      #VIRTUAL_HOST: cryptoa.it
    volumes:
      - ./wordpress:/var/www/html
      - ./conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

volumes:
  wordpress:
  db:

# chown -R www-data:www-data /var/www/html